apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-module-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-module-api
  template:
    metadata:
      labels:
        app: admin-module-api
    spec:
      containers:
        - name: admin-module-api
          image: arfaoui01/admin-module-api:1.0.1
          ports:
            - containerPort: 8090
