pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {

        stage('Build & Tag Docker Image') {
            steps {
                dir('Backend') {
                    script {
                        withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                            sh "docker build -t arfaoui01/admin-module-api:1.0.1 ."
                        }
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('Backend') {
                    script {
                        withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                            sh "docker push arfaoui01/admin-module-api:1.0.1"
                        }
                    }
                }
            }
        }
    }
}
