export * from './attributeController.service';
import { AttributeControllerService } from './attributeController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './ruleController.service';
import { RuleControllerService } from './ruleController.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AttributeControllerService, AuthenticationControllerService, CategoryControllerService, RuleControllerService, UserService];
