export * from './attributeController.service';
import { AttributeControllerService } from './attributeController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './rule.service';
import { RuleService } from './rule.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AttributeControllerService, AuthenticationControllerService, CategoryService, RuleService, UserControllerService];
