=begin
#OpenApi specification - Arfaoui

#OpenApi documentation for Admin Module Demo

The version of the OpenAPI document: 1.0
Contact: wael.arfaoui@talan.com
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
