# admin-module-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-module-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-module-ui
  template:
    metadata:
      labels:
        app: admin-module-ui
    spec:
      containers:
        - name: admin-module-ui
          image: arfaoui01/admin-module-ui:1.0.1
          ports:
            - containerPort: 80
---
# admin-module-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-module-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: admin-module-ui
