apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-module-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-module-ui
  template:
    metadata:
      labels:
        app: admin-module-ui
    spec:
      containers:
        - name: admin-module-ui
          image: arfaoui01/admin-module-ui:1.0.1
          ports:
            - containerPort: 80
