/**
 * OpenApi specification - Arfaoui
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: wael.arfaoui@talan.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface AddRequest { 
    dto?: UserDto;
    file?: Blob;
}

