/**
 * OpenApi specification - Arfaoui
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: wael.arfaoui@talan.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    firstname?: string;
    lastname?: string;
    password?: string;
    email?: string;
    company?: string;
    phone?: string;
    role?: RegisterDto.RoleEnum;
}
export namespace RegisterDto {
    export type RoleEnum = 'BUSINESSEXPERT' | 'ADMIN' | 'CONSULTANT';
    export const RoleEnum = {
        Businessexpert: 'BUSINESSEXPERT' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Consultant: 'CONSULTANT' as RoleEnum
    };
}


