/**
 * OpenApi specification - Arfaoui
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 * Contact: wael.arfaoui@talan.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface User { 
    id?: number;
    firstname?: string;
    lastname?: string;
    email?: string;
    password?: string;
    profileImagePath?: string;
    company?: string;
    phone?: string;
    role?: User.RoleEnum;
    enabled?: boolean;
    authorities?: Array<GrantedAuthority>;
    username?: string;
    accountNonLocked?: boolean;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
}
export namespace User {
    export type RoleEnum = 'BUSINESSEXPERT' | 'ADMIN' | 'CONSULTANT';
    export const RoleEnum = {
        Businessexpert: 'BUSINESSEXPERT' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Consultant: 'CONSULTANT' as RoleEnum
    };
}


