apiVersion: v1
kind: Service
metadata:
  name: admin-module-api
  labels:
    app: admin-module-api
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: admin-module-api
  type: ClusterIP
