apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-module-api
  labels:
    app: admin-module-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-module-api
  template:
    metadata:
      labels:
        app: admin-module-api
    spec:
      containers:
        - name: admin-module-api
          image: arfaoui01/admin-module-api:1.0.1
          ports:
            - containerPort: 8090
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(POSTGRES_HOST):5432/$(POSTGRES_DB)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "false"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_DATABASE
              value: postgresql
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: APPLICATION_SECURITY_JWT_SECRET_KEY
              value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            - name: APPLICATION_SECURITY_JWT_EXPIRATION
              value: "86400000"
            - name: APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION
              value: "604800000"
            - name: SERVER_PORT
              value: "8090"
