=begin
#OpenApi specification - Arfaoui

#OpenApi documentation for Admin Module Demo

The version of the OpenAPI document: 1.0
Contact: wael.arfaoui@talan.com
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AuthenticationControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationControllerApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AuthenticationControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationControllerApi' do
    it 'should create an instance of AuthenticationControllerApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AuthenticationControllerApi)
    end
  end

  # unit tests for authenticate
  # @param authentication_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthenticationResponse]
  describe 'authenticate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for refresh_token
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'refresh_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
